### PR TITLE
CIGI-410: Add home page events section

### PR DESCRIPTION
**Pull request by johnbxu**
#### Description of changes
resolves CIGIHub/cigi-tickets#410

image
image

### CODE REVIEW

**Review by gabrieltanchen — CHANGES_REQUESTED** [review]
See the screenshot below. The top row is Drupal, the bottom row is Wagtail on the same database. I don't think we ever show private events on the home page, even if it's in the future. Can you test to confirm this?

Screenshot from 2021-01-26 16-54-44

**Comment by johnbxu** [comment]
> See the screenshot below. The top row is Drupal, the bottom row is Wagtail on the same database. I don't think we ever show private events on the home page, even if it's in the future. Can you test to confirm this?

Hmmm strange. This is what I see on live right now:
image

**Comment by gabrieltanchen** [comment]
Ah okay, that makes sense then. In that case, the hover state for the private button needs to be fixed.

**Comment by johnbxu** [comment]
Removed private button hover change and added condition that takes into account events without an end time

**Review by gabrieltanchen — APPROVED** [review]

**Pull request merged**
