### PR TITLE
Add models for Drupal CIGI Worldwide Issue content type

### PR DESCRIPTION
**Pull request by gabrieltanchen**
This is 1 of 2 PR's that addresses CIGIHub/cigi-tickets#89.

Created NewsletterPage and NewsletterListPage models.

### CODE REVIEW

**Comment by johnbxu** [comment]
The `newsletter_v2_social_block` paragraph doesn't seem to be migrated.

**Comment by johnbxu** [comment]
In Drupal, many newsletter items use a content entity reference to populate title and description. Not sure if it's feasible to link the drupal content reference to the wagtail page? 

This really would only affect the newsletter V2 pages, and the majority of those do have an html file attached, so we could just display the html file instead and not worry about it?

**Comment by gabrieltanchen** [comment]
@johnbxu I've fixed the social and text blocks.

What do you mean by linking the drupal content reference? The StreamField blocks link to the Wagtail pages, which you could then pull the title and description from. Is that not enough?

**Comment by johnbxu** [comment]
I was talking about the content data stored in the drupal fields, but maybe it was intended to not migrate that over, since we have the html file? For example, here the page field is blank: 
image

**Comment by gabrieltanchen** [comment]
Yes they are migrated over, kind of. You can find the code in the migrator PR here: https://github.com/CIGIHub/wagtail-drupal-data-migrator/blob/newsletter/worker/tasks/migrate-newsletter-v2.js#L335

The migrator currently will look for publications, events, and multimedia, etc. pages. Most of the content in the newsletter though is opinions, which haven't yet been migrated so I can't really attach them yet.

**Comment by gabrieltanchen** [comment]
I created a review environment for this PR: https://cigionline-newsletter-wkkkf0lt.herokuapp.com/admin/

**Comment by johnbxu** [comment]
Ah ok. I ran the migrator again locally and now I see them locally. Sorry for making you go through the trouble.

**Pull request merged**
