### PR TITLE
CIGI-792: Add location data to event page hero section

### PR DESCRIPTION
**Pull request by johnbxu**
#### Description of changes
resolves CIGIHub/cigi-tickets#792

- Add logic that concatenates location fields and displays link to google map
- Add `event_format` field that decides if location string is shown

#### Pull Request checklist
This checklist needs to be completed before assigning reviewers. If the checklist will not be completed, please comment with the reason.
- [ ] Have you reviewed your own code changes?
- [ ] Has the issue owner reviewed your changes?
- [ ] Have you given the PR a descriptive title?
- [ ] Have you described your changes above? Always include screenshots if applicable.
- [ ] Have you pushed your latest commit to this branch?

---
#### Code Review checklist
This checklist should be completed if applicable before approving the pull request.
- [x] Have you reviewed the code changes?
- [x] Have you tested the changes on Google Chrome?
- [ ] Have you tested the changes on Safari?
- [ ] Have you tested the changes on Microsoft Edge (non-Chromium)?
- [ ] Have you tested the changes on iOS?
- [ ] Have you tested the changes on Android?

### CODE REVIEW

**Comment by yang-wang-ds** [comment]
image
image
"Virtual Event (Virtual)" reads a bit awkward.   
But that's more of a problem with lumping "Virtual Event" in `event type` in the past. The past Virtual Events do not have an `event format`, so this should not be a problem.   
But if "Virtual Event" continue to be used as an `event type`, this would occur. May need editors to weigh in on whether that would be a problem.

**Comment by yang-wang-ds** [comment]
`event format` as a required field makes it harder to quickly edit past events - would have to find out their format. Not sure if these edits happen often enough to be a problem though.

**Review by yang-wang-ds — APPROVED** [review]
Tested locally the 3 `event format` choices

**Comment by johnbxu** [comment]
> image
> 
> image
> 
> "Virtual Event (Virtual)" reads a bit awkward. But that's more of a problem with lumping "Virtual Event" in `event type` in the past. The past Virtual Events do not have an `event format`, so this should not be a problem. But if "Virtual Event" continue to be used as an `event type`, this would occur. May need editors to weigh in on whether that would be a problem.

Probably not a problem, as this event type will probably be retired from now on.

**Comment by johnbxu** [comment]
> `event format` as a required field makes it harder to quickly edit past events - would have to find out their format. Not sure if these edits happen often enough to be a problem though.

I think we should keep it required since it's an important field that affects whether or not the location will be shown. And ya, I don't think there will be many instances when a past event will need to be changed, and even then it's just a couple of clicks.

**Pull request merged**
