### PR TITLE
CIGI-205: Add data to leadership tabs

### PR DESCRIPTION
**Pull request by johnbxu**
#### Description of changes
resolves CIGIHub/cigi-tickets#205

~~- Added ajax script to senior management tab~~
  ~~* I didn't add ajax call to the board members tab because that is what's visible at the beginning~~
  ~~* I also added a check so clicks to the senior management tab after the first call won't make more calls. Not sure if this is neccessary because by default jquery ajax caches content?~~

- Adjusted filter in model to return different context variables for management and board members

### CODE REVIEW

**Comment by gabrieltanchen** [comment]
This is a good start for an ajax implementation. However, I actually don't think this is a good page for ajax. It's easier and cleaner to send all the data for both tabs and just have javascript switch between them.

**Comment by johnbxu** [comment]
Sounds good. I'll modify it to not use ajax

**Comment by johnbxu** [comment]
Removed Ajax and updated model filter

**Review by gabrieltanchen — CHANGES_REQUESTED** [review]
Can you update the query to order by person weight as well? I've migrated that data over, and should fix Rohinton's placement in the senior management tab.

**Comment by johnbxu** [comment]
> Can you update the query to order by person weight as well? I've migrated that data over, and should fix Rohinton's placement in the senior management tab.

Does this apply to all person types, or just leadership?

**Comment by gabrieltanchen** [comment]
Haven't double checked with what Drupal is doing, but just leadership. It makes sense for the experts and staff pages to only be sorted by name.

**Comment by johnbxu** [comment]
Updated sort with person weight

**Review by gabrieltanchen — APPROVED** [review]

**Pull request merged**
