### PR TITLE
CIGI-414, 415: Implement Big Tech series episode list and latest episode sections

### PR DESCRIPTION
**Pull request by johnbxu**
#### Description of changes
resolves CIGIHub/cigi-tickets#414
resolves CIGIHub/cigi-tickets#415

image
image

### CODE REVIEW

**Review by gabrieltanchen — CHANGES_REQUESTED** [review]
Seeing this for Season 2. It looks like the season trailer that was later unpublished. How is this handled in Drupal?
Screen Shot 2021-01-20 at 6 03 20 PM

Also seeing a duplicate for the upcoming Joan Donavan episode:
Screen Shot 2021-01-20 at 6 03 28 PM

**Comment by johnbxu** [comment]
> Seeing this for Season 2. It looks like the season trailer that was later unpublished. How is this handled in Drupal?
On Drupal the episode list only shows content with the big tech theme. I'm guessing the theme was removed from the trailer node after it was no longer needed. What we can do here is put a check for episode number, which would rule out the trailer.

> Also seeing a duplicate for the upcoming Joan Donavan episode:
This is because there are two of these nodes on live: 
image

The earlier one created in November doesn't have a content theme, which excluded it from the episode listing. We can just remove that node from live so it doesn't get migrated.

**Comment by johnbxu** [comment]
Or we could just do what was done in Drupal and check for the theme. This way we can include future trailers.

**Comment by johnbxu** [comment]
Added check for theme.

**Review by gabrieltanchen — APPROVED** [review]

**Pull request merged**
