### PR TITLE
CIGI-518: Style 404 page

### PR DESCRIPTION
**Pull request by johnbxu**
#### Description of changes
resolves CIGIHub/cigi-tickets#518

image

### CODE REVIEW

**Comment by johnbxu** [comment]
There are some issues with this:
1. Because the page is just a template, not a Page model, a lot of the <head> info is missing
2. I ran into a lot of trouble getting the webpacked css and js to work properly, as it treated it as a html file, but it doesn't seem to be a problem on live? I'm not sure if there will be issues with that

Should we make the 404 page into a Page model and setup 404 handler to direct to that? Or maybe hardcode all the <head> items?

**Comment by gabrieltanchen** [comment]
@johnbxu what do you mean by "a lot of the info is missing"? What info do you need?

How did you get this working locally?

**Comment by johnbxu** [comment]
Sorry I meant to say info in <head>, since they read from `self`, which doesn't exist in the 404 page context.

I switched debug to false, and it loads, but only if the cigionline webpack files are already cached. So I have to load a normal page, turn debug to false, then load the 404.

**Review by gabrieltanchen — APPROVED** [review]
I can't seem to get the 404 page working locally. I get 500 errors when I set `DEBUG=False`. Not worth the time to investigate now when this code looks fine.

**Pull request merged**
