### PR TITLE
Structure CSS

### PR DESCRIPTION
**Pull request by johnbxu**
- Added folder structure for css
- Added Normalize.css and reset

image

### CODE REVIEW

**Comment by gabrieltanchen** [comment]
Why do you think we need normalize.css? Have you had instances with our styling where the browser defaults have led to issues?

**Comment by gabrieltanchen** [comment]
The only thing that makes me nervous with normalize is that it's been almost 2 years since the last release. I have no problem adding this since it's very small, but don't copy and paste the file in. There's an npm package for it - use that.

**Comment by johnbxu** [comment]
> Why do you think we need normalize.css? Have you had instances with our styling where the browser defaults have led to issues?

I have ran into a few instances where defaults were inconsistent and I had to hunt down the issue. The Drupal site uses normalize so I figured I would add it here as well. 

I added the npm package.

**Review by gabrieltanchen — APPROVED** [review]
👍

**Pull request merged**
