### PR TITLE
CIGI-474: Implement Staff page

### PR DESCRIPTION
**Pull request by johnbxu**
#### Description of changes
resolves CIGIHub/cigi-tickets#474

image
image

### CODE REVIEW

**Comment by gabrieltanchen** [comment]
@johnbxu there are merge conflicts here. Let me know when they're resolved and then I'll review

**Comment by johnbxu** [comment]
Resolved conflicts

**Review by gabrieltanchen — CHANGES_REQUESTED** [review]
The functionality here looks good, but I don't think this should use the `SearchTable` component. Since (1) this isn't searching, (2) this uses a different "paginator", and (3) this doesn't make API calls when a new page is selected.

This can be achieved by a component that just does a single API call then loads the `StaffListing` components.

**Comment by johnbxu** [comment]
Refactored to not use SearchTable component

**Review by gabrieltanchen — APPROVED** [review]

**Comment by johnbxu** [comment]
Oh yes, it makes a lot more sense to use a different api instead. Thanks!

**Pull request merged**
