### PR TITLE
cigi-451: styling in the series for indigenous land series

### PR DESCRIPTION
**Pull request by zylene**
#### Description of changes
resolves CIGIHub/cigi-tickets#451
In the series styling

### CODE REVIEW

**Review by gabrieltanchen — CHANGES_REQUESTED** [review]
This should have a left margin on mobile:
Screenshot from 2021-01-29 09-28-19

**Comment by zylene** [comment]
> This should have a left margin on mobile:
> Screenshot from 2021-01-29 09-28-19

this is fixed

**Review by gabrieltanchen — CHANGES_REQUESTED** [review]
The left margin is still present on large screens (only occurs on the article page).
Screen Shot 2021-02-01 at 10 43 54 AM

**Comment by zylene** [comment]
fixed, those margins! thanks.

**Review by gabrieltanchen — APPROVED** [review]

**Pull request merged**
